root_path: ../../
project_name: wider_face_base_model
seed: 0
max_iterations: 140000
log_smooth_window: 10
snapshot_iter: 5000
eval_iter_list: [90000, 140000]

architecture: WiderFaceBaseNet
pretrain_weights: ./pretrain_weights/resnet101-5d3b4d8f.pth
weight_init_fn: NormalWeightInit
num_classes: 1
clip_gradients: ClipGradients

optimizer: SGDOptimizer
warmup_strategy: LinearWarmup
lr: 0.01

criterion: MogCriterion
criterion_dsfd: Criterion

train_feed: TrainFeed
validation_set: WiderFaceValSet
generate_anchors_fn: GeneartePriorBoxes
preprocess_fn: BasePreprocess

WiderFaceBaseNet:
  backbone: ResNet
  fpn: LFPN
  pred_net: MogPredNet

ResNet:
  depth: 101

LFPN:
  c2_out_ch: 256
  c3_out_ch: 512
  c4_out_ch: 1024
  c5_out_ch: 2048
  c6_mid_ch: 512
  c6_out_ch: 512
  c7_mid_ch: 128
  c7_out_ch: 256
  out_dsfd_ft: True

MogPredNet:
  num_anchor_per_pixel: 1
  input_ch_list: [256, 256, 256, 256, 256, 256]
  use_deep_head: True
  deep_head_with_gn: True 
  deep_head_ch: 512
  use_ssh: True
  use_dsfd: True
  retina_cls_weight_init_fn: RetinaClsWeightInit

Criterion:
  cls_loss_weight: 1
  loc_loss_weight: 2
  cls_loss_fn: FocalLoss
  loc_loss_fn: SmoothL1Loss

FocalLoss:
  alpha: 0.25
  gamma: 2.0

SmoothL1Loss:
  sigma: 3

TrainFeed:
  dataset: WiderFaceTrainSet
  add_dsfd_label: True

WiderFaceTrainSet:
  anchor_target_fn: AnchorTarget
  data_aug_settings: DataAugSettings
  out_dsfd_label: True


BasePreprocess:
  data_aug_settings: DataAugSettings
  normalize_pixel: True
  use_rgb: True
  img_mean: [0.485, 0.456, 0.406]
  img_std: [0.229, 0.224, 0.225]

MogCriterion:
  cls_loss_weight: 1
  loc_loss_weight: 2
  cls_loss_fn: FocalLoss
  loc_loss_fn: SmoothL1Loss

AnchorTarget:
  rpn_positive_overlap: 0.35
  rpn_negative_overlap: 0.35
  gt_match_maxoverlap_anchor: True
  nomalized_compute_overlap: False

GeneartePriorBoxes:
  scale_list: [0.68]
  aspect_ratio_list: [1.0]
  stride_list: [4,8,16,32,64,128]
  anchor_size_list: [16,32,64,128,256,512]

SGDOptimizer:
  momentum: 0.9
  weight_decay: 1e-4

LinearWarmup:
  #lr: 0.001
  warm_up_iter: 3000 
  step_list: [110000, 140000, 160000]
  ini_lr: 1e-6
  gamma: 0.1

ClipGradients:
  max_norm: 5
  norm_type: 2
